name: Hello.txt Workflow

on: 
  push: 
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout Code
        run: ls -la
      - name: Read and Output
        run: cat Hello.txt
      
        
    
